### register usera z potwierdzeniem wysłanym na maila
POST http://localhost:3000/api/user/register
content-type: application/json

{   
  "name": "name",
  "lastName": "lastName",
  "email":"jakub.dragosz@o2.pl",
  "password":"password"
}

### user potwierdza rejestrację z użyciem tokena plus mail że konto aktywne
GET http://localhost:3000/api/user/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impha3ViLmRyYWdvc3pAbzIucGwiLCJsYXN0bmFtZSI6Imxhc3ROYW1lIiwibmFtZSI6Im5hbWUiLCJpYXQiOjE2NTQwOTk0MzksImV4cCI6MTY1NDEwMTIzOX0.b1tiOkKItFhWBHVKw4IX1lMTyoKFJ0y86EvnfOAtijw

### logowanie z odesłaniem tokena po zalogowaniu - od tej pory każde żądanie zawiera token
POST http://localhost:3000/api/user/login
content-type: application/json

{
  "email":"jakub.dragosz@o2.pl",
  "password":"password"
}

### json all users - funkcja pomocnicza dla testów
GET http://localhost:3000/api/users HTTP/1.1

###pobranie danych usera
GET http://localhost:3000/api/user HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impha3ViLmRyYWdvc3pAbzIucGwiLCJsYXN0bmFtZSI6Imxhc3ROYW1lIiwibmFtZSI6Im5hbWUiLCJpYXQiOjE2NTQwOTk0MzksImV4cCI6MTY1NDEwMTIzOX0.b1tiOkKItFhWBHVKw4IX1lMTyoKFJ0y86EvnfOAtijw
### aktualizacja danych usera w jego profilu
PATCH http://localhost:3000/api/user HTTP/1.1
authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWVAZW1haWwyLnBsIiwibGFzdG5hbWUiOiJsYXN0TmFtZSIsIm5hbWUiOiJmaXJzdE5hbWUiLCJpYXQiOjE2NTQwMjk4OTgsImV4cCI6MTY1NDAzMTY5OH0.rdT0lZ-j0GSDZSs-YzVvuLpPwzRrjyV-YyGcg_lzHl4

{
  "email":"aa@b.com"
}

### wysłanie zdjęcia profilowego
POST http://localhost:3000/api/user/profile HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWVAZW1haWwyLnBsIiwibGFzdG5hbWUiOiJsYXN0TmFtZSIsIm5hbWUiOiJmaXJzdE5hbWUiLCJpYXQiOjE2NTQwMjk4OTgsImV4cCI6MTY1NDAzMTY5OH0.rdT0lZ-j0GSDZSs-YzVvuLpPwzRrjyV-YyGcg_lzHl4
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.jpg"
Content-Type: image/jpeg

< ./input.jpg

------FormBoundary1234
Content-Disposition: form-data; name="album"
Content-Type: text/plain

12345
------FormBoundary1234

### wylogowanie
GET http://localhost:3000/api/user/logout HTTP/1.1
