### zwraca dostępne metody -> info dla programisty (opcjonalnie)
GET http://localhost:3000/api/filters HTTP/1.1

### dane o zdjęciu, potrzebne do jego obróbki
GET http://localhost:3000/api/filters/metadata/1653251607340 HTTP/1.1

### użycie konkretnego filtra, dane o nim przekazujemy w jsonie
PATCH http://localhost:3000/api/filters HTTP/1.1
content-type: application/json

{
  "id":4,
  "id_obrazka":1653257541699,
  "options": [
        {
            "name": "rotate",
            "value":90
        }
    ]
}

//nazwa obrazka, nie id

### wyswietlenie zdjecia
GET http://localhost:3000/uploads/nazwa_albumu/upload_a6a526ba40bc0c82f794818615184674-tint.jpg HTTP/1.1