### logowanie z odesłaniem tokena po zalogowaniu - od tej pory każde żądanie zawiera token
POST http://localhost:3000/api/user/login HTTP/1.1
content-type: application/json

{
  "email":"name@email2.pl",
  "password":"password"
}

###JSON all users
GET http://localhost:3000/api/users HTTP/1.1

###pobranie danych usera
GET http://localhost:3000/api/user HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWVAZW1haWwyLnBsIiwibGFzdG5hbWUiOiJsYXN0TmFtZSIsIm5hbWUiOiJmaXJzdE5hbWUiLCJpYXQiOjE2NTM4NjA2MDgsImV4cCI6MTY1Mzg2MjQwOH0.6mWnw657r1EMB5KbnSuOyMpdif3A2MtHuox7DzpEk_Y
### aktualizacja danych usera w jego profilu
PATCH http://localhost:3000/api/user HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWVAZW1haWwyLnBsIiwibGFzdG5hbWUiOiJsYXN0TmFtZSIsIm5hbWUiOiJmaXJzdE5hbWUiLCJpYXQiOjE2NTM4NjA2MDgsImV4cCI6MTY1Mzg2MjQwOH0.6mWnw657r1EMB5KbnSuOyMpdif3A2MtHuox7DzpEk_Y

{
  "email":"aa@b.com"
}

### wysłanie zdjęcia profilowego
POST http://localhost:3000/api/user/profile HTTP/1.1

### wylogowanie
GET http://localhost:3000/api/user/logout HTTP/1.1